### PR TITLE
Add unit tests for files which has no external dependencies

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
Hi Fibery Team,
Noticed that there were no tests in this project. Adding some with this PR.
For fetcher, api and api-call. I would suggest to look into mock api/contract testing instead of plain unit tests. 
Want to get setup in place before starting discussion on integration tests.

### CODE REVIEW

**Comment by Mavrin** [comment]
@Maxim-Filimonov 😞  Sorry, I missed your pull request.

**Comment by Maxim-Filimonov** [comment]
@Mavrin any feedback?

**Comment by Mavrin** [comment]
Need to fix build step.

**Comment by Mavrin** [comment]
@Maxim-Filimonov Thanks

**Pull request merged**
